# Generated by Django 3.1.7 on 2021-02-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Subject',
            new_name='subject',
        ),
    ]
